version: 2.1
jobs:
  lin_build:
    machine: 
      image: ubuntu-2004:202010-01 

    steps:
      - checkout
      - run: python3 setup.py sdist
      - run: python3 -m pip install dist/FeatureCloud-0.0.16.tar.gz
workflows:
  version: 2
  build-all:
    jobs:
      - lin_build
