version: 2.1
jobs:
  lin_build:
    machine: 
      image: ubuntu-2004:202010-01 

    steps:
      - checkout
      - run: sh rebuild.sh
workflows:
  version: 2
    build-all:
      jobs:
        - lin_build
