version: 2.1

orbs:
    win: circleci/windows@4.1.1

jobs:
  lin_build:
    machine: 
      image: ubuntu-2004:202010-01 

    steps:
      - checkout
      - run: python3 setup.py sdist
      - run: python3 -m pip install dist/FeatureCloud-0.0.16.tar.gz
      - run: featurecloud controller --help
      - run: featurecloud controller start
      - run: featurecloud controller status
      - run: featurecloud controller stop

  mac_build:
    macos: 
      xcode: 12.5.1

    steps:
      - checkout
      - run: python3 setup.py sdist
      - run: python3 -m pip install dist/FeatureCloud-0.0.16.tar.gz
      - run: open /Applications/Docker.app
      - run: featurecloud controller --help
      - run: featurecloud controller start
      - run: featurecloud controller status
      - run: featurecloud controller stop

  win_build:
    executor: win/default

    steps:
      - checkout
      - run: choco install python3 --version=3.8
      - run: docker --version
      - run: choco install docker
      - run: python setup.py sdist
      - run: python -m pip install dist/FeatureCloud-0.0.16.tar.gz
      - run: featurecloud controller --help
      - run: featurecloud controller start
      - run: featurecloud controller status
      - run: featurecloud controller stop

workflows:
  version: 2
  build-all:
    jobs:
      - lin_build
      - mac_build
      - win_build
