version: 2.1

jobs:
  lin_build:
    machine: 
      image: ubuntu-2004:202010-01 

    steps:
      - checkout
      - run: python3 setup.py sdist
      - run: python3 -m pip install dist/FeatureCloud-0.0.17.tar.gz
      - run: featurecloud controller --help
      - run: featurecloud controller start
      - run: featurecloud controller status
      - run: featurecloud controller stop
      - run: python3 -m pip install pytest
      - run: pytest tests/test_pip_package.py

workflows:
  version: 2
  build-all:
    jobs:
      - lin_build
      - mac_build
